### ISSUE TITLE
Flask Server Not Starting in Generate Component

### ISSUE THREAD

**Issue by pkini2002** [Mayukh-Mondal-Dev/Decentralized-Document-Verifcation-System#1]
I cloned the project and followed the setup steps for the Generate component, but the Flask server didn't start as expected. Below are the commands I used to start the flask server:

```
pip install virtualenv
```

```
virtualenv env
env/Scripts/activate
```

```
pip install -r requirements.txt
```

```
cd Generate
```

```
python generate.py
```

Unfortunately, the Flask server isn't running after executing the above command. I followed similar steps for the Validate Component and didn't encounter any issues.

Any help in setting up the project and running the Flask server would be highly appreciated!

Thanks in advance!

**Comment by Mayukh-Mondal-Dev** [comment]
Well after executing the exact same commands as of yours in my system, the flask server is running without any issue.
You can check the screenshots attached:
![image](https://github.com/Mayukh-Mondal-Dev/Decentralized-Document-Verifcation-System/assets/92180806/7cebc8f3-aa0f-4cf5-a5f2-f4ef82d55f43)
![image](https://github.com/Mayukh-Mondal-Dev/Decentralized-Document-Verifcation-System/assets/92180806/85700263-66d4-47e0-bf46-c98572b6d32f)

I will suggest to re-install the requirements and re-execute the commands.
Preferable use Python version 11.

Hope you find it helpful! 
And please update me regarding the same

**Comment by pkini2002** [comment]
Well thats sounds strange! I tried updating my Python version from 3.9 to 3.11 but still facing the same issue.
I tried cloning the project again and re-running all the commands. Below are the screenshots attached:

<img width="953" alt="a" src="https://github.com/Mayukh-Mondal-Dev/Decentralized-Document-Verifcation-System/assets/84091455/f8229534-1511-4b54-acab-dfcf1ac2ff1d">
<img width="959" alt="b" src="https://github.com/Mayukh-Mondal-Dev/Decentralized-Document-Verifcation-System/assets/84091455/232ea71f-cbe4-44b0-a519-2640ef6b619e">
<img width="955" alt="c" src="https://github.com/Mayukh-Mondal-Dev/Decentralized-Document-Verifcation-System/assets/84091455/951919cd-f8c4-4232-892c-e6e65028e894">

**Comment by Mayukh-Mondal-Dev** [comment]
Please check the port availability, I am using the default port here 5000, you can change it in the generate.py

like here:


```
if __name__ == "__main__":
    # block_thread = threading.Thread(target=generate_block_every_second)
    # block_thread.daemon = True
    # block_thread.start()
    app.run(debug=True, port=5005)
```
 
please check after updating the code!

**Comment by pkini2002** [comment]
Thanks a lot, @Mayukh-Mondal-Dev! The problem is resolved, and the Flask server is running successfully now. The issue was that, even though I had installed Python Version 3.11 and verified it in my terminal, the virtual environment Python version was defaulting back to my older version (3.9.7), creating the whole mess. Anyways, thank you so much for helping me debug my issue!
